services:
  _defaults:
    autowire: false
    autoconfigure: false

  ContaoThemesShop\VacancyCalendar\EventListener\Dca\VacancyCalendarReservationDcaListener:
    arguments:
      - '@netzmacht.contao_toolkit.template_renderer'
      - '@netzmacht.contao_toolkit.contao.input_adapter'
      - '@netzmacht.contao_toolkit.contao.message_adapter'
      - '@netzmacht.contao_toolkit.contao.system_adapter'
      - '@netzmacht.contao_toolkit.contao.controller_adapter'
      - '@translator'
      - '@ContaoThemesShop\VacancyCalendar\Model\ReservationRepository'
