services:
  _defaults:
    autowire: false
    autoconfigure: false

  ContaoThemesShop\VacancyCalendar\Controller\FrontendModule\VacancyCalendarController:
    arguments:
      - '@netzmacht.contao_toolkit.template_renderer'
      - '@netzmacht.contao_toolkit.routing.scope_matcher'
      - '@netzmacht.contao_toolkit.response_tagger'
      - '@router'
      - '@translator'
      - '@ContaoThemesShop\VacancyCalendar\Model\CalendarRepository'
      - '@ContaoThemesShop\VacancyCalendar\Model\ReservationRepository'
