services:
    _defaults:
        autowire: false
        autoconfigure: true

    ContaoThemesShop\VacancyCalendar\Controller\FrontendModule\VacancyCalendarController:
        arguments:
            - '@ContaoThemesShop\VacancyCalendar\Model\CalendarRepository'
            - '@ContaoThemesShop\VacancyCalendar\Model\ReservationRepository'
            - '@translator'
